sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.98.47.249:3307/sharding_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: sharding
        password: sharding
        maxPoolSize: 50
        minPoolSize: 1
    config:
      sharding:
        default-data-source-name: ds0
      props:
        sql.show: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    caffeine:
      spec: initialCapacity=5,maximumSize=500,expireAfterWrite=60s
