spring:
  main:
    allow-bean-definition-overriding: true
sharding:
  jdbc:
    datasource:
      names: ds0,ds1,ds0-slave,ds1-slave
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.77:3306/db0?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: xin123456
        maxPoolSize: 50
        minPoolSize: 1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.77:3306/db1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: xin123456
        maxPoolSize: 50
        minPoolSize: 1
      ds0-slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3307/db0?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: mysql123456
        maxPoolSize: 50
        minPoolSize: 1
      ds1-slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3307/db1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: mysql123456
        maxPoolSize: 50
        minPoolSize: 1
    config:
      sharding:
        tables:
          employee:
            actual-data-nodes: ds$->{0..1}.employee
            #key-generator:
              #column: id
              #type: SNOWFLAKE
            database-strategy:
              standard:
                sharding-column: id
                preciseAlgorithmClassName: com.can.sharding.OrderIdShardingAlgorithm
        default-data-source-name: ds0
      props:
        sql.show: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true